services:
  postgres:
    image: kartoza/postgis:latest
    container_name: qgis-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: nicolas06
      POSTGRES_USER: nicolas
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: qgis-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: nwjs.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: nicolas06
    restart: always
    ports:
      - 8080:80
    depends_on:
      - postgres
    networks:
      - postgres-network
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  postgres-network:
    driver: bridge
  
volumes:
  myapp:
    external: true
